function zVisualize(prmLTE, txSig, rxSig, yRec, dataRx, csr, nS)
% Constellation Scopes & Spectrum Analyzer (new version using spectrumAnalyzer)

persistent hScope1 hScope2 hSpecAnalyzer

%% Create Scopes Once
if isempty(hSpecAnalyzer)

    % ===== 1. Constellation before equalizer =====
    hScope1 = comm.ConstellationDiagram( ...
        'ShowReferenceConstellation', false, ...
        'XLimits', [-2 2], ...
        'YLimits', [-2 2], ...
        'Position', figposition([5 60 20 25]), ...
        'Name', 'Before Equalizer');

    % ===== 2. Constellation after equalizer =====
    hScope2 = comm.ConstellationDiagram( ...
        'ShowReferenceConstellation', false, ...
        'XLimits', [-2 2], ...
        'YLimits', [-2 2], ...
        'Position', figposition([6 21 20 25]), ...
        'Name', 'After Equalizer');

    if verLessThan('comm','5.5')
        hScope1.SymbolsToDisplay = prmLTE.numDataResources;
        hScope2.SymbolsToDisplay = prmLTE.numDataResources;
    end

    % ===== 3. NEW: spectrumAnalyzer =====
    hSpecAnalyzer = spectrumAnalyzer( ...
        'SampleRate', prmLTE.chanSRate, ...
        'SpectrumType', 'power-density', ...   % NOTE: lowercase naming (new API)
        'PowerUnits', 'dBW', ...
        'RBWSource', 'property', ...
        'RBW', 15000, ...
        'FrequencySpan', 'Span and center frequency', ...
        'Span', prmLTE.BW, ...
        'CenterFrequency', 0, ...
        'SpectralAverages', 10, ...
        'Title', 'Transmitted & Received Signal Spectrum', ...
        'YLimits', [-110 -60], ...
        'YLabel', 'PSD', ...
        'ShowLegend', true);
end

%% ===== Compute received signal after equalizer for spectrum =====
yRecGrid    = REmapper_1Tx(yRec, csr, nS, prmLTE);
yRecGridSig = OFDMTx(yRecGrid, prmLTE);

%% ===== Update spectrum analyzer =====
hSpecAnalyzer( ...
    [ SymbSpec(txSig, prmLTE), ...
      SymbSpec(rxSig, prmLTE), ...
      SymbSpec(yRecGridSig, prmLTE) ] );

%% ===== Update Constellation Diagram =====
if nS ~= 0 && nS ~= 10
    hScope1(dataRx(:,1));
    hScope2(yRec(:,1));
end

end
%-------------
function y = SymbSpec(in, prmLTE)
N = prmLTE.N;
cpLenR = prmLTE.cpLen0;

y = complex(zeros(N+cpLenR, 1));
y(:,1) = in(end-(N+cpLenR)+1:end, 1);
end
